### ISSUE TITLE
Taskwarrior 2.6.0 no longer syncs

### ISSUE THREAD

**Issue by williamjameshandley** [freecinc/freecinc-issues#15]
Many thanks for this excellent service. I've found that since I've updated to taskwarrior 2.6.0 I can no longer sync:

```
Sync failed.  The Taskserver returned error: 500 ERROR: '253402102800' is not a valid date in the 'm/d/Y' format.
```

The issue is that 2.6.0 now supports 64 bit timestamps, with a corresponding update to the `someday` keyword to be greater than the year 2038. Is there any possibility of an upgrade to taskwarrior 2.6.0?

**Comment by djmitche** [comment]
The server runs taskd, not taskwarrior, and is running the latest release.  If there's another release of taskd, we'll upgrade freecinc to use it.  Until that time, I think you'll need to stick to dates before 2038 :)

I'm currently working on a project to build a new backend for taskwarrior sync, which would be more robust in a number of ways.  The most relevant to this issue is, the new sync model does not require the server to have any understanding of the data being sync'd -- why does the server need to know that "253402102800" is a date??

Anyway, that means two things: one, this may be fixed when that work is complete. And two, this might _not_ be fixed before that time.  Note that the last taskd release was in 2015!

At any rate, please do file an issue for taskd on the [taskserver](https://github.com/GothenburgBitFactory/taskserver) issue tracker, as that's where the bug is.
